import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

<link
  rel="stylesheet"
  href="http://localhost:3000/_next/static/css/app/layout.css?v=1712575393984"
  as="style"
/>;
const interFontFamily = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={interFontFamily.className}>
      <body className="container  max-w-full">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
